export {default as EditIcon} from "./pencil.svg"
export {default as DeleteIcon} from "./bin.svg"
export {default as ViewIcon} from "./eye.svg"
export {default as BoatIcon} from "./boat.svg"
export {default as ExclaimIcon} from "./exlaim.svg"
export {default as SuccessIcon} from "./success.svg"